- name: "{{ playbook_name }} Deploy sonarqube"
  hosts: sonar
  become: true
  vars:
    _prefix: "deploy_sonarqube :"
    max_map_count: 262144
    compose_dir: "{{ server_home }}/sonar"

  roles:
    - role: setup
    - role: geerlingguy.certbot
      tags:
        - setup
        - certbot
    - role: sonar
      tags:
        - deploy
