- name: "{{ _prefix }} Deploy GitHub Actions Runner"
  hosts: ci
  become: true
  gather_facts: true
  no_log: false
  vars:
    _prefix: "deploy_github_runner :"
  vars_prompt:
    - name: access_token
      prompt: github token

  roles:
    - role: setup

  tasks:
    - name: "{{ _prefix }} Setup github runner for every repository"
      tags:
        - github_runner
        - deploy
      include_role:
        role: monolithprojects.github_actions_runner
      loop: "{{ github_repositories }}"
      loop_control:
        loop_var: github_repo
