# Generated by Django 4.0.1 on 2022-03-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
