# Generated by Django 4.0.1 on 2022-04-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0005_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(choices=[('upvote', 1), ('nothing', 0), ('downvote', -1)], default=0),
        ),
    ]
