# Generated by Django 3.1.6 on 2021-03-08 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_books_bookid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='book author')),
                ('title', models.CharField(max_length=200, verbose_name='book title')),
                ('link', models.CharField(max_length=200, verbose_name='chapter link')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='chapter number')),
                ('text', models.TextField(verbose_name='chapter text')),
                ('link', models.CharField(max_length=200, verbose_name='chapter link')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.RemoveField(
            model_name='chapters',
            name='book',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Chapters',
        ),
    ]
