# Generated by Django 3.1.7 on 2021-03-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210309_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.CharField(default='title', max_length=200, verbose_name='chapter title'),
        ),
    ]
