# Generated by Django 3.1.7 on 2021-03-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_sitemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemap',
            name='title',
            field=models.CharField(default='no-url', max_length=200, verbose_name='chapter link'),
        ),
        migrations.AlterField(
            model_name='sitemap',
            name='url',
            field=models.CharField(default='no-title', max_length=200, verbose_name='chapter link'),
        ),
    ]
