# Generated by Django 3.1.7 on 2021-03-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20210310_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='link',
        ),
        migrations.AddField(
            model_name='book',
            name='sourceLink',
            field=models.CharField(default='no source link', max_length=200, verbose_name='chapter link'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='no author', max_length=100, verbose_name='book author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='no title', max_length=200, verbose_name='book title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.CharField(default='/no-url/', max_length=100, unique=True, verbose_name='book url'),
        ),
        migrations.AlterField(
            model_name='sitemap',
            name='title',
            field=models.CharField(default='no-title', max_length=200, verbose_name='chapter title'),
        ),
        migrations.AlterField(
            model_name='sitemap',
            name='url',
            field=models.CharField(default='no-url', max_length=200, verbose_name='chapter link'),
        ),
    ]
