# Generated by Django 3.1.7 on 2021-03-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20210312_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.CharField(default='/no-url/', max_length=300, verbose_name='book url'),
        ),
    ]
