# Generated by Django 3.1.7 on 2021-03-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20210312_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='no author', max_length=200, verbose_name='book author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='siteUrl',
            field=models.CharField(default='/no-url/', max_length=200, verbose_name='book url'),
        ),
    ]
