# Generated by Django 3.1.7 on 2021-03-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20210312_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='chapters',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
