# Generated by Django 3.1.7 on 2021-03-12 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20210312_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNumber', models.IntegerField(verbose_name='chapter number')),
                ('content', models.TextField(verbose_name='chapter text')),
                ('title', models.CharField(default='title', max_length=200, verbose_name='chapter title')),
                ('sourceUrl', models.CharField(max_length=200, verbose_name='chapter link')),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='books.book')),
            ],
        ),
    ]
