# Generated by Django 3.1.7 on 2021-03-12 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='books.book'),
        ),
    ]
