- name: sonar
  tags:
    - deploy
    - sonar
  block:
    - name: >-
        {{ playbook_name }} | Create docker-compose directories
      ansible.builtin.file:
        path: "{{ compose_dir }}/{{ item.path }}"
        state: directory
        mode: "{{ item.mode }}"
      with_community.general.filetree: templates/sonar/
      loop_control:
        label: "{{ item.path }}"
      when: item.state == "directory"

    - name: >-
        {{ playbook_name }} | Copy docker-compose templates
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ compose_dir }}/{{ item.path }}"
      with_community.general.filetree: templates/sonar/
      loop_control:
        label: "{{ item.path }}"
      when: item.state == "file"

    - name: >-
        {{ playbook_name }} | Set vm.max_map_count kernel setting to
        {{ max_map_count }} for embedded elasticsearch
        https://stackoverflow.com/a/57998152
      become: true
      ansible.builtin.shell: sysctl -w vm.max_map_count={{ max_map_count }}

    - name: >-
        {{ playbook_name }} | Run docker-compose up
      community.docker.docker_compose:
        project_src: "{{ server_home }}/sonar"
        remove_orphans: true
        pull: true
      register: docker_compose_up

    - name: >-
        "{{ playbook_name }} | Show output"
      ansible.builtin.debug: { var: docker_compose_up }
