# https://pentacent.medium.com/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
version: "3"
services:
    nginx:
        container_name: nginx
        image: nginx:1-alpine
        restart: unless-stopped
        ports:
            - 443:443
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - "{{ compose_dir }}/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "{{ compose_dir }}/other:/etc/nginx/other:ro"

    sonar:
        container_name: sonar
        image: sonarqube:9-community
        restart: unless-stopped
        environment:
            SONARQUBE_JDBC_USERNAME: sonarqube
            SONARQUBE_JDBC_PASSWORD: sonarpass
            SONARQUBE_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs

    db:
        image: postgres:15-alpine
        container_name: db
        restart: unless-stopped
        environment:
            POSTGRES_USER: sonarqube
            POSTGRES_PASSWORD: sonarpass
            POSTGRES_DB: sonarqube
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data

volumes:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    postgresql:
    postgresql_data: