#cloud-config

# merging config
merge_how:
  - name: list
    settings: [append]
  - name: dict
    settings: [no_replace, recurse_list]

# general stuff
ssh_pwauth: false
disable_root: true
repo_update: true
repo_upgrade: true

# install packages
packages:
  - git
  - jq
  - expect

# users
# all passwords are disabled by default
users:
  - name: "${server_user}"
    gecos: admin user
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - "${key_main}"
      - "${key_personal}"
