version: "3.1"

services:
    postgres:
        container_name: tianyi_postgres
        image: postgres:14-alpine
        restart: always
        environment:
            POSTGRES_DB: tianyi
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: "spo,h-6'383<YN%P<abr[l5Xv!o*O=+}"
        volumes:
            - ./database_extensions.sql:/docker-entrypoint-initdb.d/database_extensions.sql:ro
        networks:
            - tianyi

    redis:
        container_name: tianyi_redis
        image: redis:7-alpine
        restart: always
        networks:
            - tianyi
        command: redis-server --requirepass "spo,h-6'383<YN%P<abr[l5Xv!o*O=+}"

    tianyi:
        container_name: tianyi_server
        image: kongrentian/tianyi:${CI_COMMIT_REF_NAME}
        volumes:
            - ./tianyi.yml:/app/tianyi.yml:ro
        networks:
            - tianyi
        depends_on:
            - postgres
            - redis

    nginx:
        container_name: tianyi_nginx
        image: nginx:1.23-alpine
        volumes:
            - ./tianyi.conf:/etc/nginx/conf.d/tianyi.conf:ro
            - ./ssl:/etc/nginx/ssl:ro
        networks:
            - tianyi
        ports:
            - "443:8080"
        depends_on:
            - tianyi
networks:
    tianyi:
