name: GHPages

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  mkdocs:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Cache
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install packages
        run: pip install mkdocs-material mkdocs-monorepo-plugin

      - name: Deploy to GHPages
        run: mkdocs gh-deploy --force
