name: GHPages

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

jobs:
  mkdocs:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Cache
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: |
            .cache
            docs/projects

      - name: Install packages
        run: pip install mkdocs-material mkdocs-monorepo-plugin mkdocs-minify-plugin

      - name: Clone repositories
        working-directory: docs
        run: |
          mkdir -p projects
          cd projects
          read -ra repos < <(
            gh repo list shishifubing                         \
              --source                                        \
              --visibility public                             \
              --limit 999                                     \
              --json name                                     \
              --template '{{ range . }}{{ .name }} {{ end }}'
          )

          for repo in "${repos[@]}"; do
            {
              git clone "https://github.com/shishifubing/${repo}" \
                || git --git-dir "${repo}/.git" pull
            } &
          done

          wait
          ls

          for repo in "${repos[@]}"; do
            mkdir -p "${repo}/docs"
            test -f "${repo}/docs/index.md"                     \
              || cp "${repo}/README.md" "${repo}/docs/index.md"
            touch "${repo}/mkdocs.yml"
          done

      - name: Deploy to GHPages
        run: mkdocs gh-deploy --force
