name: Tag

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - README.md
      - .github/**/*.md
      - .github/FUNDING.yml
      - .github/ISSUE_TEMPLATE/**

jobs:
  tag:
    uses: shishifubing/ci-actions-common/.github/workflows/tag.yml@main
    secrets: inherit
